In [31]:
import tensorflow as tf

a = tf.constant(3)
b = tf.constant(5)

sess = tf.Session()

sess.run(a+b)


8

In [32]:
import tensorflow as tf

aa = tf.Variable([1,2,3])
ba = tf.Variable([3,5,8])

init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    print(aa.eval(sess))
    print(aa.eval())  # use default session 'sess'
    print(sess.run(tf.matadd(aa,bb))

SyntaxError: invalid syntax (<ipython-input-32-a1ca13d2f25e>, line 12)

In [38]:
import numpy as np

x1 = [[1,3,5,7,9],[2,8,6,3,1]]
x2 = [[2,8,6,3,1],[1,3,5,7,8]]
dist = tf.reduce_sum(tf.abs(tf.add(x1,tf.neg(x2))), reduction_indices=1)
idx_min = tf.arg_min(dist, 0)
idx_max = tf.arg_max(dist, 0)

x3 = [1,3,5,7,9]
x4 = [[3],[5],[6],[8],[1]]
mtx = tf.abs(tf.add(x3,tf.neg(x4)))
dist2 = tf.reduce_sum(tf.abs(tf.add(x3,tf.neg(x4))), reduction_indices=1)

sess = tf.Session()

print(sess.run(dist))
print(sess.run(idx_min))
print(sess.run(idx_max))
print(sess.run(mtx))
print(sess.run(dist2))


[19 18]
1
0
[[2 0 2 4 6]
 [4 2 0 2 4]
 [5 3 1 1 3]
 [7 5 3 1 1]
 [0 2 4 6 8]]
[14 12 13 17 20]


In [55]:
import tensorflow as tf

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

w = tf.random_normal([1], mean=1, stddev=0.1)
print w

c = tf.add(tf.mul(a, w), b)

with tf.Session() as sess:
    print sess.run(w)
    print sess.run(c, feed_dict={a:2, b:3})


Tensor("random_normal_12:0", shape=(1,), dtype=float32)
[ 0.8677606]
[ 5.12616348]


In [83]:
import tensorflow as tf
import numpy as np
import pandas as pd

x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print x.shape

y = tf.transpose(x, [2,1,0])
print y
print y.get_shape()

y1 = tf.reshape(y, [-1,y.get_shape().as_list()[0]])
print y1

y1 = tf.reshape(y, [-1,-1,y.get_shape().as_list()[0]])
print y1

y1 = tf.reshape(y, [-1,1,y.get_shape().as_list()[0]])
print y1

z = tf.reshape(y, [-1, 2])
print z
print z.get_shape()
print z.name

z1 = tf.reshape(z, [-1,z.get_shape().as_list()[0]])
print z1


(2, 2, 3)
Tensor("transpose_21:0", shape=(3, 2, 2), dtype=int64)
(3, 2, 2)
Tensor("Reshape_22:0", shape=(4, 3), dtype=int64)
Tensor("Reshape_23:0", shape=(?, ?, 3), dtype=int64)
Tensor("Reshape_24:0", shape=(4, 1, 3), dtype=int64)
Tensor("Reshape_25:0", shape=(6, 2), dtype=int64)
(6, 2)
Reshape_25:0
Tensor("Reshape_26:0", shape=(2, 6), dtype=int64)


In [5]:
from tensorflow.python.framework import ops
from tensorflow.python.framework import dtypes

a = [1,3,5]
b = ['a','b','c']

at = ops.convert_to_tensor(a, dtype=dtypes.int32)
bt = ops.convert_to_tensor(b, dtype=dtypes.string)

print at
print bt

Tensor("Const_4:0", shape=(3,), dtype=int32) (3,)
Tensor("Const_5:0", shape=(3,), dtype=string)


In [13]:
import numpy as np

r = np.arange(0.0,10.0)
raw_data = np.dstack((r,r,r,r))[0]
raw_target = np.array([[0,1,0]]*10)
print(r)
print(raw_data)
print(raw_target)


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]
 [ 9.  9.  9.  9.]]
[[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]]
